M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu25.10.1 date 2026-09-08T22:15:22
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-08T22:15:22+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu25.10.1
; #@! TF.FileFunction,MixedPlating,1,2
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X5.0Y-10.0
X5.0Y-12.54
T2
X3.0Y-3.0
X22.0Y-17.0
M30
